import React, { useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Button, Card, Empty, Field, Heading, Row, Screen } from '../components/ui';
import { useApp } from '../context/AppContext';
import { colors, spacing } from '../theme';
import { message } from '../lib/supabase';

const empty = { name: '', phone: '+92', email: '', address: '' };
export function CustomersScreen({ navigation }: any) {
  const app = useApp(); const [search, setSearch] = useState(''); const [form, setForm] = useState<any>(empty); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return app.customers.filter(c => !q || `${c.name} ${c.phone} ${c.email} ${c.address}`.toLowerCase().includes(q)); }, [search, app.customers]);
  const save = async () => { if (!form.name.trim() || !form.phone.trim() || !form.address.trim()) return setError('Name, phone, and address are required.'); setBusy(true); try { const customer = await app.saveCustomer(form); setOpen(false); setForm(empty); navigation.getParent()?.navigate('CustomerDetail', { customerId: customer.id }); } catch (e) { setError(message(e)); } finally { setBusy(false); } };
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><View style={styles.titleRow}><Heading title="Customers" subtitle={`${app.customers.length} customer records`} /><Pressable accessibilityLabel="Add customer" style={styles.add} onPress={() => { setForm(empty); setError(''); setOpen(true); }}><Ionicons name="person-add" size={22} color={colors.white} /></Pressable></View><Field label="Search customer records" value={search} onChangeText={setSearch} placeholder="Name, phone, email, or address" /><Card>{filtered.map(c => <Row key={c.id} title={c.name} subtitle={`${c.phone} · ${c.source === 'portal' ? 'Portal signup' : c.source === 'both' ? 'Admin + portal' : 'Admin record'}`} onPress={() => navigation.getParent()?.navigate('CustomerDetail', { customerId: c.id })} right={<Ionicons name="chevron-forward" size={20} color={colors.muted} />} />)}{!filtered.length ? <Empty icon="people-outline" title="No customers found" detail="Add a customer or adjust your search." /> : null}</Card>
    <Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setOpen(false)}><Screen><View style={styles.modalHead}><Heading title="New customer" subtitle="Create a delivery and billing profile." /><Pressable accessibilityLabel="Close" onPress={() => setOpen(false)}><Ionicons name="close" size={28} color={colors.ink} /></Pressable></View><Card>{error ? <Text style={styles.error}>{error}</Text> : null}<Field label="Full name" value={form.name} onChangeText={name => setForm({ ...form, name })} /><Field label="Phone" value={form.phone} onChangeText={phone => setForm({ ...form, phone })} keyboardType="phone-pad" /><Field label="Email (optional)" value={form.email} onChangeText={email => setForm({ ...form, email })} keyboardType="email-address" autoCapitalize="none" /><Field label="Delivery address" value={form.address} onChangeText={address => setForm({ ...form, address })} multiline style={{ minHeight: 90, textAlignVertical: 'top', paddingTop: 14 }} /><Button label="Create customer" icon="checkmark" onPress={save} loading={busy} /></Card></Screen></Modal>
  </Screen>;
}
const styles = StyleSheet.create({ titleRow: { flexDirection: 'row', justifyContent: 'space-between' }, add: { marginTop: 2, width: 50, height: 50, backgroundColor: colors.primary, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, modalHead: { flexDirection: 'row', justifyContent: 'space-between' }, error: { color: colors.danger, backgroundColor: '#FFF0F0', padding: 12, marginBottom: spacing.md, borderRadius: 10 } });
