import React, { useMemo, useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import * as Haptics from 'expo-haptics';
import { Badge, Button, Card, Empty, Field, Heading, Row, Screen, Stat } from '../components/ui';
import { useApp } from '../context/AppContext';
import { shareInvoicePdf } from '../lib/exports';
import { message } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';

type Period = 'daily' | 'weekly' | 'monthly' | 'all';
const money = (v: number) => `PKR ${Number(v || 0).toLocaleString()}`;
function inPeriod(date: string, period: Period) { const d = new Date(date); const now = new Date(); if (period === 'daily') return d.toDateString() === now.toDateString(); if (period === 'weekly') return d >= new Date(Date.now() - 6 * 86400000); if (period === 'monthly') return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); return true; }

export function CustomerDetailScreen({ route, navigation }: any) {
  const app = useApp(); const customer = app.customers.find(x => x.id === route.params.customerId); const [editing, setEditing] = useState(false); const [form, setForm] = useState<any>(customer || {}); const [period, setPeriod] = useState<Period>('monthly'); const [busy, setBusy] = useState('');
  const customerSales = useMemo(() => app.sales.filter(x => x.customer_id === customer?.id), [app.sales, customer?.id]); const displayed = customerSales.filter(x => inPeriod(x.created_at, period)); const invoices = app.invoices.filter(x => x.customer_id === customer?.id);
  const stats = { orders: displayed.length, bottles: displayed.reduce((a, x) => a + Number(x.quantity), 0), revenue: displayed.reduce((a, x) => a + Number(x.total_amount), 0) };
  if (!customer) return <Screen><Empty title="Customer not found" detail="This customer may have been removed." /></Screen>;
  const pickPhoto = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: .65, base64: true }); if (!result.canceled && result.assets[0].base64) setForm({ ...form, photo: `data:${result.assets[0].mimeType || 'image/jpeg'};base64,${result.assets[0].base64}` }); };
  const save = async () => { setBusy('save'); try { await app.saveCustomer(form); setEditing(false); } catch (e) { Alert.alert('Could not save', message(e)); } finally { setBusy(''); } };
  const createInvoice = async () => { setBusy('invoice'); try { const invoice = await app.createInvoice(customer, displayed); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); Alert.alert('Invoice generated', `${invoice.invoice_number} is ready.`, [{ text: 'View invoice', onPress: () => navigation.navigate('InvoiceDetail', { invoiceId: invoice.id }) }, { text: 'Share PDF', onPress: () => shareInvoicePdf(invoice) }]); } catch (e) { Alert.alert('Could not generate invoice', message(e)); } finally { setBusy(''); } };
  const remove = () => Alert.alert('Delete customer?', 'This permanently removes the customer and linked operational records.', [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await app.deleteCustomer(customer.id); navigation.goBack(); } catch (e) { Alert.alert('Could not delete', message(e)); } } }]);
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><View style={styles.header}><Pressable accessibilityLabel="Go back" style={styles.back} onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><View style={{ flex: 1 }}><Heading title={customer.name} subtitle="Customer profile and account ledger" /></View></View>
    <Card><View style={styles.profile}>{form.photo ? <Image source={{ uri: form.photo }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Text style={styles.initial}>{customer.name.charAt(0)}</Text></View>}<View style={{ flex: 1 }}><Text style={styles.name}>{customer.name}</Text><Text style={styles.meta}>{customer.phone}</Text><Badge label={customer.auth_user_id ? 'App user' : 'Admin record'} tone={customer.auth_user_id ? 'success' : 'default'} /></View><Pressable accessibilityLabel="Edit customer" style={styles.iconButton} onPress={() => { setForm(customer); setEditing(!editing); }}><Ionicons name={editing ? 'close' : 'create-outline'} size={21} color={colors.primary} /></Pressable></View>{editing ? <View style={styles.edit}><Pressable onPress={pickPhoto} style={styles.photoAction}><Ionicons name="camera" color={colors.primary} size={18} /><Text style={styles.photoText}>Choose profile photo</Text></Pressable><Field label="Full name" value={form.name} onChangeText={name => setForm({ ...form, name })} /><Field label="Phone" value={form.phone} onChangeText={phone => setForm({ ...form, phone })} keyboardType="phone-pad" /><Field label="Email" value={form.email || ''} onChangeText={email => setForm({ ...form, email })} /><Field label="Address" value={form.address} onChangeText={address => setForm({ ...form, address })} multiline /><Button label="Save changes" onPress={save} loading={busy === 'save'} /><Button label="Delete customer" tone="danger" onPress={remove} /></View> : <View style={styles.contact}><Text style={styles.contactText}><Ionicons name="mail-outline" /> {customer.email || 'No email'}</Text><Text style={styles.contactText}><Ionicons name="location-outline" /> {customer.address}</Text></View>}</Card>
    <View style={styles.periods}>{(['daily', 'weekly', 'monthly', 'all'] as Period[]).map(x => <Pressable key={x} onPress={() => setPeriod(x)} style={[styles.period, period === x && styles.periodOn]}><Text style={[styles.periodText, period === x && styles.periodTextOn]}>{x}</Text></Pressable>)}</View><View style={styles.stats}><Stat icon="receipt-outline" label="Orders" value={stats.orders} /><Stat icon="water-outline" label="Bottles" value={stats.bottles} tone={colors.cyan} /><Stat icon="cash-outline" label="Revenue" value={money(stats.revenue)} tone={colors.success} /><Stat icon="document-text-outline" label="Invoices" value={invoices.length} tone="#8B5CF6" /></View>
    <Button label="Generate invoice for this period" icon="document-text" onPress={createInvoice} loading={busy === 'invoice'} disabled={!displayed.length} />
    <Card title={`Invoices (${invoices.length})`}>{invoices.map(invoice => <Row key={invoice.id} title={invoice.invoice_number} subtitle={`${new Date(invoice.invoice_date).toLocaleDateString()} · ${money(invoice.total_amount)}`} onPress={() => navigation.navigate('InvoiceDetail', { invoiceId: invoice.id })} right={<Badge label={invoice.payment_status} tone={invoice.payment_status === 'paid' ? 'success' : 'warning'} />} />)}{!invoices.length ? <Empty icon="document-outline" title="No invoices" detail="Choose a period with sales and generate the first invoice." /> : null}</Card>
    <Card title={`Purchase history (${displayed.length})`}>{displayed.map(sale => <Row key={sale.id} title={`${sale.bottle_type} × ${sale.quantity}`} subtitle={`${new Date(sale.created_at).toLocaleString()}${sale.notes ? ` · ${sale.notes}` : ''}`} right={<Text style={styles.amount}>{money(sale.total_amount)}</Text>} />)}{!displayed.length ? <Empty title="No purchases in this period" detail="Change the period or record a sale." /> : null}</Card>
  </Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', gap: 10 }, back: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border }, profile: { flexDirection: 'row', alignItems: 'center', gap: 13 }, avatar: { width: 68, height: 68, borderRadius: 22 }, avatarFallback: { width: 68, height: 68, borderRadius: 22, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, initial: { color: colors.white, fontSize: 25, fontWeight: '900' }, name: { color: colors.ink, fontSize: 20, fontWeight: '900' }, meta: { color: colors.muted, marginVertical: 4 }, iconButton: { width: 46, height: 46, borderRadius: 14, backgroundColor: '#EDF5FF', alignItems: 'center', justifyContent: 'center' }, contact: { marginTop: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, gap: 9 }, contactText: { color: colors.muted, lineHeight: 20 }, edit: { marginTop: spacing.lg }, photoAction: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 15 }, photoText: { color: colors.primary, fontWeight: '800' }, periods: { flexDirection: 'row', gap: 7, marginBottom: spacing.md }, period: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border }, periodOn: { backgroundColor: colors.primary }, periodText: { color: colors.muted, fontSize: 11, textTransform: 'capitalize', fontWeight: '800' }, periodTextOn: { color: colors.white }, stats: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, amount: { color: colors.ink, fontWeight: '900', fontSize: 12 } });
