import React, { useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { Badge, Card, Empty, Heading, Row, Screen } from '../components/ui';
import { Donut, LottieMetric, Sparkline } from '../components/visuals';
import { bottleTypes, useApp } from '../context/AppContext';
import { colors, radius, spacing } from '../theme';

const money = (n: number) => `PKR ${Math.round(n || 0).toLocaleString()}`;
export function DashboardScreen() {
  const app = useApp(); const now = new Date();
  const metrics = useMemo(() => {
    const today = app.sales.filter(x => new Date(x.created_at).toDateString() === now.toDateString()); const month = app.sales.filter(x => { const d = new Date(x.created_at); return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); });
    const active = new Set(app.sales.filter(x => new Date(x.created_at) >= new Date(Date.now() - 30 * 86400000)).map(x => x.customer_id)).size;
    const days = Array.from({ length: 14 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - (13 - i)); return app.sales.filter(x => new Date(x.created_at).toDateString() === d.toDateString()).reduce((a, x) => a + Number(x.total_amount), 0); });
    return { today, month, active, daily: days, revenue: month.reduce((a, x) => a + Number(x.total_amount), 0), bottles: today.reduce((a, x) => a + Number(x.quantity), 0), pending: app.orders.filter(x => x.status === 'pending').length, unread: app.notifications.filter(x => !x.read).length };
  }, [app.sales, app.orders, app.notifications]);
  const totalStock = Object.values(app.inventory).reduce((a, x) => a + Number(x), 0); const low = bottleTypes.filter(x => Number(app.inventory[x] || 0) <= Number(app.settings.lowStockThreshold || 20));
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><Heading title={`Good ${new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 18 ? 'afternoon' : 'evening'}, ${app.admin?.name?.split(' ')[0] || 'Admin'}`} subtitle="Your delivery command center is live." />
    <LinearGradient colors={['#0B1533', '#163D7A']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.hero}><View style={styles.heroTop}><View><Text style={styles.kicker}>MONTHLY REVENUE</Text><Text style={styles.heroValue}>{money(metrics.revenue)}</Text><Text style={styles.heroSub}>{metrics.month.length} sales entries · {metrics.active} active customers</Text></View><View style={styles.live}><View style={styles.dot} /><Text style={styles.liveText}>LIVE</Text></View></View><Sparkline values={metrics.daily} color="#69D7FF" height={94} /></LinearGradient>
    <View style={styles.metrics}><LottieMetric kind="delivered" title="Bottles today" value={metrics.bottles} detail={`${metrics.today.length} completed sales`} tone={colors.cyan} /><LottieMetric kind="approved" title="Pending orders" value={metrics.pending} detail={`${metrics.unread} unread alerts`} tone="#F59E0B" /><LottieMetric kind="approved" title="Customers" value={app.customers.length} detail={`${metrics.active} active this month`} tone="#8B5CF6" /><LottieMetric kind="delivered" title="Inventory" value={totalStock} detail={low.length ? `${low.length} low-stock types` : 'Stock levels healthy'} tone={low.length ? colors.danger : colors.success} /></View>
    <Card title="Operational health" action={<Badge label="Live" tone="success" />}><View style={styles.donuts}><Donut value={metrics.active} total={app.customers.length} color={colors.primary} label="Active" /><Donut value={app.orders.filter(x => x.status === 'delivered').length} total={app.orders.length} color={colors.success} label="Delivered" /><Donut value={app.invoices.filter(x => x.payment_status === 'paid').length} total={app.invoices.length} color="#8B5CF6" label="Paid" /></View></Card>
    {low.length ? <Card title="Stock alerts">{low.map(type => <Row key={type} title={type === 'Gallon' ? '19L Gallon' : type} subtitle={`${app.inventory[type] || 0} units remaining`} right={<View style={styles.alertIcon}><Ionicons name="warning" color={colors.danger} size={19} /></View>} />)}</Card> : null}
    <Card title="Recent sales">{app.sales.slice(0, 5).map(sale => <Row key={sale.id} title={sale.customers?.name || 'Customer'} subtitle={`${sale.bottle_type} × ${sale.quantity} · ${new Date(sale.created_at).toLocaleDateString()}`} right={<Text style={styles.amount}>{money(sale.total_amount)}</Text>} />)}{!app.sales.length ? <Empty title="No sales yet" detail="Recorded sales will appear here." /> : null}</Card>
  </Screen>;
}
const styles = StyleSheet.create({ hero: { borderRadius: 25, padding: spacing.lg, marginBottom: spacing.md, overflow: 'hidden' }, heroTop: { flexDirection: 'row', justifyContent: 'space-between' }, kicker: { color: '#90AED6', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, heroValue: { color: colors.white, fontSize: 29, fontWeight: '900', marginTop: 6 }, heroSub: { color: '#9FB8D9', fontSize: 11, marginTop: 5 }, live: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start', backgroundColor: 'rgba(47,174,96,.16)', borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 6 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#5EE29B' }, liveText: { color: '#7EF0AC', fontWeight: '900', fontSize: 9 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: spacing.sm }, donuts: { flexDirection: 'row', justifyContent: 'space-around', flexWrap: 'wrap' }, alertIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#FFF0F0', alignItems: 'center', justifyContent: 'center' }, amount: { color: colors.ink, fontWeight: '900', fontSize: 12 } });
