import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import LottieView from 'lottie-react-native';
import * as Haptics from 'expo-haptics';
import { Badge, Button, Card, Empty, Heading, Row, Screen } from '../components/ui';
import { useApp } from '../context/AppContext';
import { shareInvoicePdf } from '../lib/exports';
import { message } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';

const approved = require('../assets/lottie/approved.json'); const money = (v: number) => `PKR ${Number(v || 0).toLocaleString()}`;
export function InvoiceDetailScreen({ route, navigation }: any) {
  const app = useApp(); const invoice = app.invoices.find(x => x.id === route.params.invoiceId); const [busy, setBusy] = useState('');
  if (!invoice) return <Screen><Empty title="Invoice not found" detail="Refresh the invoice register and try again." /></Screen>;
  const p = invoice.payload || {}; const history = p.history || [];
  const update = async (patch: any, key: string) => { setBusy(key); try { await app.updateInvoice(invoice.id, patch); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } catch (e) { Alert.alert('Could not update invoice', message(e)); } finally { setBusy(''); } };
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><View style={styles.header}><Pressable accessibilityLabel="Go back" style={styles.back} onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><View style={{ flex: 1 }}><Heading title={invoice.invoice_number} subtitle="Invoice review and validation" /></View></View>
    <Card><View style={styles.invoiceHead}><View><Text style={styles.eyebrow}>HIMALIYA SPRING WATER</Text><Text style={styles.company}>{p.company?.name || 'Himaliya Spring Water'}</Text><Text style={styles.muted}>{p.company?.address || 'Sialkot Cantt'}</Text><Text style={styles.muted}>{p.company?.phone}</Text></View><View style={styles.statusArea}>{invoice.validated ? <LottieView source={approved} autoPlay loop={false} style={styles.approved} /> : <Ionicons name="document-text-outline" size={40} color={colors.primary} />}<Badge label={invoice.payment_status} tone={invoice.payment_status === 'paid' ? 'success' : 'warning'} /></View></View><View style={styles.rule} /><View style={styles.people}><View style={{ flex: 1 }}><Text style={styles.label}>BILL TO</Text><Text style={styles.person}>{p.customer?.name || 'Customer'}</Text><Text style={styles.muted}>{p.customer?.phone}</Text><Text style={styles.muted}>{p.customer?.address}</Text></View><View style={{ flex: 1 }}><Text style={styles.label}>PREPARED BY</Text><Text style={styles.person}>{p.preparedBy?.name || 'Admin'}</Text><Text style={styles.muted}>{p.preparedBy?.role}</Text><Text style={styles.muted}>{p.preparedBy?.email}</Text></View></View><View style={styles.summary}><View><Text style={styles.summaryLabel}>ENTRIES</Text><Text style={styles.summaryValue}>{p.summary?.entryCount || history.length}</Text></View><View><Text style={styles.summaryLabel}>QUANTITY</Text><Text style={styles.summaryValue}>{p.summary?.totalQty || invoice.total_qty}</Text></View><View><Text style={styles.summaryLabel}>TOTAL</Text><Text style={styles.summaryValue}>{money(p.summary?.totalAmount || invoice.total_amount)}</Text></View></View></Card>
    <Card title="Line items">{history.map((x: any, index: number) => <Row key={`${x.date}-${index}`} title={`${x.bottleType} × ${x.quantity}`} subtitle={`${new Date(x.date).toLocaleDateString()} · ${money(x.pricePerBottle)} each`} right={<Text style={styles.amount}>{money(x.totalAmount)}</Text>} />)}{!history.length ? <Empty title="No line items" detail="The invoice payload contains no purchase entries." /> : null}</Card>
    <Card title="Invoice controls"><View style={styles.actions}><Button label={invoice.payment_status === 'paid' ? 'Mark unpaid' : 'Mark paid'} tone={invoice.payment_status === 'paid' ? 'secondary' : 'success'} onPress={() => update({ payment_status: invoice.payment_status === 'paid' ? 'unpaid' : 'paid' }, 'payment')} loading={busy === 'payment'} /><Button label={invoice.validated ? 'Validated' : 'Validate invoice'} tone={invoice.validated ? 'secondary' : 'primary'} icon="shield-checkmark" disabled={invoice.validated} onPress={() => update({ validated: true }, 'validate')} loading={busy === 'validate'} /><Button label="Share PDF" tone="secondary" icon="share-outline" onPress={() => shareInvoicePdf(invoice).catch(e => Alert.alert('Could not create PDF', message(e)))} /></View></Card>
  </Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', gap: 10 }, back: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border }, invoiceHead: { flexDirection: 'row', justifyContent: 'space-between' }, eyebrow: { color: colors.primary, fontWeight: '900', fontSize: 10, letterSpacing: 1 }, company: { color: colors.ink, fontSize: 21, fontWeight: '900', marginTop: 5 }, muted: { color: colors.muted, fontSize: 12, lineHeight: 18 }, statusArea: { alignItems: 'center', gap: 6 }, approved: { width: 62, height: 50 }, rule: { height: 3, borderRadius: 3, backgroundColor: colors.primary, marginVertical: 20 }, people: { flexDirection: 'row', gap: 14 }, label: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: .8 }, person: { color: colors.ink, fontWeight: '800', marginVertical: 5 }, summary: { marginTop: 20, borderRadius: radius.md, backgroundColor: '#EDF5FF', padding: 14, flexDirection: 'row', justifyContent: 'space-between' }, summaryLabel: { color: colors.muted, fontSize: 9, fontWeight: '800' }, summaryValue: { color: colors.ink, fontWeight: '900', marginTop: 5, fontSize: 14 }, amount: { color: colors.ink, fontWeight: '900', fontSize: 12 }, actions: { gap: spacing.sm } });
