import React, { useEffect, useRef } from 'react';
import { Animated, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PulseOrb } from '../components/visuals';
import { colors, radius, spacing } from '../theme';
import { useApp } from '../context/AppContext';

const features = [
  ['people-outline', 'Customer ledger', 'Profiles, purchases, balances, and invoices in one place.'],
  ['cube-outline', 'Delivery workflow', 'Accept requests, price orders, and confirm doorstep delivery.'],
  ['analytics-outline', 'Live intelligence', 'Revenue, stock, bottle mix, and customer growth visualized.'],
] as const;

export function LandingScreen({ navigation }: any) {
  const { session } = useApp(); const fade = useRef(new Animated.Value(0)).current; const slide = useRef(new Animated.Value(22)).current;
  useEffect(() => { Animated.parallel([Animated.timing(fade, { toValue: 1, duration: 520, useNativeDriver: true }), Animated.spring(slide, { toValue: 0, damping: 18, useNativeDriver: true })]).start(); }, [fade, slide]);
  const proceed = () => navigation.navigate(session ? 'Admin' : 'Login');
  return <LinearGradient colors={[colors.navy, '#102D64', '#1877D2']} style={{ flex: 1 }}><SafeAreaView style={{ flex: 1 }}><ScrollView contentContainerStyle={styles.scroll}>
    <View style={styles.nav}><View style={styles.brand}><View style={styles.logo}><Text style={styles.logoText}>HS</Text></View><View><Text style={styles.brandName}>Himaliya Spring</Text><Text style={styles.brandSub}>Water operations</Text></View></View><Pressable onPress={proceed} style={styles.navButton}><Text style={styles.navButtonText}>{session ? 'Dashboard' : 'Admin sign in'}</Text></Pressable></View>
    <Animated.View style={[styles.hero, { opacity: fade, transform: [{ translateY: slide }] }]}><View style={styles.heroCopy}><View style={styles.kicker}><View style={styles.liveDot} /><Text style={styles.kickerText}>SIALKOT CANTT · LIVE WATER OPERATIONS</Text></View><Text style={styles.headline}>Every delivery.{`\n`}Every bottle.{`\n`}One clear view.</Text><Text style={styles.subhead}>Run customer accounts, daily sales, delivery requests, invoices, and inventory from a focused mobile command center.</Text><View style={styles.actions}><Pressable onPress={proceed} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>{session ? 'Open dashboard' : 'Start managing'}</Text><Ionicons name="arrow-forward" size={20} color={colors.navy} /></Pressable></View></View><View style={styles.orb}><PulseOrb /></View></Animated.View>
    <View style={styles.statStrip}><View><Text style={styles.statValue}>19L</Text><Text style={styles.statLabel}>Gallon routes</Text></View><View style={styles.divider} /><View><Text style={styles.statValue}>Live</Text><Text style={styles.statLabel}>Customer ledger</Text></View><View style={styles.divider} /><View><Text style={styles.statValue}>Fast</Text><Text style={styles.statLabel}>Sales entry</Text></View></View>
    <View style={styles.section}><Text style={styles.sectionEyebrow}>BUILT FOR THE ROUTE</Text><Text style={styles.sectionTitle}>Operations without the paperwork.</Text>{features.map(([icon, title, detail], index) => <Animated.View key={title} style={[styles.feature, { opacity: fade, transform: [{ translateY: Animated.multiply(slide, (index + 1) * 0.25) }] }]}><LinearGradient colors={['rgba(255,255,255,0.16)', 'rgba(255,255,255,0.06)']} style={styles.featureGradient}><View style={styles.featureIcon}><Ionicons name={icon} size={23} color="#7DD3FC" /></View><View style={{ flex: 1 }}><Text style={styles.featureTitle}>{title}</Text><Text style={styles.featureDetail}>{detail}</Text></View><Ionicons name="chevron-forward" color="#83A7D8" size={20} /></LinearGradient></Animated.View>)}</View>
    <Text style={styles.footer}>© {new Date().getFullYear()} Himaliya Spring Water · Sialkot Cantt</Text>
  </ScrollView></SafeAreaView></LinearGradient>;
}
const styles = StyleSheet.create({ scroll: { padding: spacing.md, paddingBottom: 40 }, nav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, brand: { flexDirection: 'row', alignItems: 'center', gap: 10 }, logo: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, logoText: { color: colors.primary, fontWeight: '900' }, brandName: { color: colors.white, fontWeight: '800', fontSize: 15 }, brandSub: { color: '#9CB6DC', fontSize: 11 }, navButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 14, borderRadius: radius.pill, borderWidth: 1, borderColor: 'rgba(255,255,255,.28)' }, navButtonText: { color: colors.white, fontSize: 12, fontWeight: '800' }, hero: { marginTop: 54 }, heroCopy: {}, kicker: { flexDirection: 'row', alignItems: 'center', gap: 8 }, liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#5EE29B' }, kickerText: { color: '#A9C7EE', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, headline: { color: colors.white, fontSize: 43, lineHeight: 48, fontWeight: '900', letterSpacing: -1.7, marginTop: 17 }, subhead: { color: '#C1D2EB', fontSize: 16, lineHeight: 25, marginTop: 18 }, actions: { flexDirection: 'row', marginTop: 25 }, primary: { minHeight: 54, borderRadius: 17, backgroundColor: '#7DD3FC', flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 20 }, primaryText: { color: colors.navy, fontWeight: '900', fontSize: 15 }, pressed: { opacity: .82, transform: [{ scale: .98 }] }, orb: { alignItems: 'center', marginVertical: 18 }, statStrip: { backgroundColor: 'rgba(5,15,43,.42)', borderWidth: 1, borderColor: 'rgba(255,255,255,.12)', borderRadius: 22, padding: 18, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' }, statValue: { color: colors.white, fontWeight: '900', textAlign: 'center', fontSize: 18 }, statLabel: { color: '#94AED1', fontSize: 10, marginTop: 3 }, divider: { width: 1, height: 32, backgroundColor: 'rgba(255,255,255,.13)' }, section: { marginTop: 56 }, sectionEyebrow: { color: '#7DD3FC', fontSize: 11, fontWeight: '900', letterSpacing: 1.2 }, sectionTitle: { color: colors.white, fontSize: 29, fontWeight: '900', marginTop: 9, marginBottom: 20 }, feature: { marginBottom: 12, borderRadius: 20, overflow: 'hidden' }, featureGradient: { minHeight: 108, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,.1)', borderRadius: 20 }, featureIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: 'rgba(125,211,252,.12)', alignItems: 'center', justifyContent: 'center' }, featureTitle: { color: colors.white, fontWeight: '800', fontSize: 16 }, featureDetail: { color: '#AFC4E1', fontSize: 12, lineHeight: 18, marginTop: 4 }, footer: { color: '#7796BF', fontSize: 11, textAlign: 'center', marginTop: 36 } });
