import React, { useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { Button, Card, Empty, Field, Heading, Row, Screen } from '../components/ui';
import { useApp } from '../context/AppContext';
import { colors, radius, spacing } from '../theme';
import { message } from '../lib/supabase';

const bottles = ['Small Bottle', 'Medium Bottle', 'Large Bottle', 'Gallon'];
export function SalesScreen() {
  const app = useApp(); const [customerId, setCustomerId] = useState(''); const [bottleType, setBottleType] = useState('Gallon'); const [quantity, setQuantity] = useState('1'); const [price, setPrice] = useState(String(app.prices.Gallon || '')); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false);
  const total = useMemo(() => Number(quantity || 0) * Number(price || 0), [quantity, price]);
  const record = async () => { if (!customerId) return Alert.alert('Select a customer'); if (Number(quantity) <= 0 || Number(price) < 0) return Alert.alert('Check quantity and price'); setBusy(true); try { await app.recordSale({ customerId, bottleType, quantity: Number(quantity), price: Number(price), notes }); setQuantity('1'); setNotes(''); Alert.alert('Sale recorded', 'The dashboard and customer ledger are now updated.'); } catch (e) { Alert.alert('Could not record sale', message(e)); } finally { setBusy(false); } };
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><Heading title="Daily sales" subtitle="Fast bottle entry for delivery rounds." /><Card title="Record sale"><Text style={styles.label}>Customer</Text><View style={styles.picker}><Picker selectedValue={customerId} onValueChange={setCustomerId}><Picker.Item label="Choose customer" value="" />{app.customers.map(c => <Picker.Item key={c.id} label={`${c.name} · ${c.phone}`} value={c.id} />)}</Picker></View><Text style={styles.label}>Bottle type</Text><View style={styles.picker}><Picker selectedValue={bottleType} onValueChange={(value) => { setBottleType(value); setPrice(String(app.prices[value] || '')); }}>{bottles.map(type => <Picker.Item key={type} label={type === 'Gallon' ? '19L Gallon' : type} value={type} />)}</Picker></View><View style={styles.two}><Field label="Quantity" value={quantity} onChangeText={setQuantity} keyboardType="number-pad" style={styles.half} /><Field label="Price per bottle" value={price} onChangeText={setPrice} keyboardType="decimal-pad" style={styles.half} /></View><Field label="Notes" value={notes} onChangeText={setNotes} placeholder="Optional route note" /><View style={styles.total}><Text style={styles.totalLabel}>Sale total</Text><Text style={styles.totalValue}>PKR {total.toLocaleString()}</Text></View><Button label="Record sale" icon="checkmark-circle" onPress={record} loading={busy} /></Card><Card title="Recent entries">{app.sales.slice(0, 8).map(s => <Row key={s.id} title={s.customers?.name || 'Customer'} subtitle={`${s.bottle_type} × ${s.quantity} · ${new Date(s.created_at).toLocaleDateString()}`} right={<Text style={styles.amount}>PKR {Number(s.total_amount).toLocaleString()}</Text>} />)}{!app.sales.length ? <Empty title="No sales recorded" detail="Your first delivery entry will appear here." /> : null}</Card></Screen>;
}
const styles = StyleSheet.create({ label: { color: colors.ink, fontSize: 13, fontWeight: '700', marginBottom: 7 }, picker: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, marginBottom: spacing.md, overflow: 'hidden', justifyContent: 'center' }, two: { flexDirection: 'row', gap: spacing.sm }, half: { flex: 1 }, total: { flexDirection: 'row', justifyContent: 'space-between', padding: spacing.md, backgroundColor: '#EDF5FF', borderRadius: radius.md, marginBottom: spacing.sm }, totalLabel: { color: colors.muted, fontWeight: '700' }, totalValue: { color: colors.primary, fontWeight: '900', fontSize: 18 }, amount: { color: colors.ink, fontWeight: '800', fontSize: 12 } });
