import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { Button, Card, Field, Heading, Row, Screen } from '../components/ui';
import { useApp } from '../context/AppContext';
import { colors, radius, spacing } from '../theme';
import { message, supabase } from '../lib/supabase';
import { exportSalesCsv } from '../lib/exports';

const bottleTypes = ['Small Bottle', 'Medium Bottle', 'Large Bottle', 'Gallon'];
export function SettingsScreen() {
  const app = useApp(); const [form, setForm] = useState(app.settings); const [prices, setPrices] = useState<Record<string, number>>(app.prices); const [inventory, setInventory] = useState<Record<string, number>>(app.inventory); const [busy, setBusy] = useState(false);
  useEffect(() => { setForm(app.settings); setPrices(app.prices); setInventory(app.inventory); }, [app.settings, app.prices, app.inventory]);
  const save = async () => { setBusy(true); try { await app.saveSettings(form, prices, inventory); Alert.alert('Settings saved'); } catch (e) { Alert.alert('Could not save', message(e)); } finally { setBusy(false); } };
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><Heading title="Settings" subtitle="Business details, pricing, inventory, exports, and order controls." /><Card title="Business"><Field label="Business name" value={String(form.businessName || '')} onChangeText={businessName => setForm({ ...form, businessName })} /><Field label="Phone" value={String(form.businessPhone || '')} onChangeText={businessPhone => setForm({ ...form, businessPhone })} keyboardType="phone-pad" /><Field label="Address" value={String(form.businessAddress || '')} onChangeText={businessAddress => setForm({ ...form, businessAddress })} /><Field label="Invoice due days" value={String(form.invoiceDueDays ?? 7)} onChangeText={invoiceDueDays => setForm({ ...form, invoiceDueDays: Number(invoiceDueDays) })} keyboardType="number-pad" /></Card><Card title="Bottle prices">{bottleTypes.map(type => <Field key={type} label={type === 'Gallon' ? '19L Gallon' : type} value={String(prices[type] ?? '')} onChangeText={value => setPrices({ ...prices, [type]: Number(value) })} keyboardType="decimal-pad" />)}</Card><Card title="Live bottle inventory">{bottleTypes.map(type => <Field key={type} label={`${type === 'Gallon' ? '19L Gallon' : type} units`} value={String(inventory[type] ?? '')} onChangeText={value => setInventory({ ...inventory, [type]: Number(value) })} keyboardType="number-pad" />)}<Field label="Low-stock warning threshold" value={String(form.lowStockThreshold ?? 20)} onChangeText={lowStockThreshold => setForm({ ...form, lowStockThreshold: Number(lowStockThreshold) })} keyboardType="number-pad" /></Card><Card title="Order controls"><Toggle label="Auto-accept orders" value={Boolean(form.autoAcceptOrders)} onChange={autoAcceptOrders => setForm({ ...form, autoAcceptOrders })} /><Toggle label="Admin order notifications" value={form.adminOrderNotifications !== false} onChange={adminOrderNotifications => setForm({ ...form, adminOrderNotifications })} /><Toggle label="Require delivery confirmation" value={form.requireDeliveryConfirmation !== false} onChange={requireDeliveryConfirmation => setForm({ ...form, requireDeliveryConfirmation })} /><Toggle label="Allow customer cancellation" value={form.allowCustomerCancellation !== false} onChange={allowCustomerCancellation => setForm({ ...form, allowCustomerCancellation })} /><Field label="Daily cutoff time" value={String(form.orderCutoffTime || '18:00')} onChangeText={orderCutoffTime => setForm({ ...form, orderCutoffTime })} /></Card><Card title="Data export"><Text style={styles.exportCopy}>Share the complete sales ledger as CSV for accounting or backup.</Text><Button label="Export sales CSV" tone="secondary" icon="download-outline" onPress={() => exportSalesCsv(app.customers, app.sales).catch(e => Alert.alert('Could not export', message(e)))} /></Card><Button label="Save all settings" icon="save" onPress={save} loading={busy} /></Screen>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} onValueChange={onChange} trackColor={{ false: '#CCD4E1', true: '#9CC7FF' }} thumbColor={value ? colors.primary : '#F5F5F5'} /></View>; }

export function ProfileScreen() {
  const app = useApp(); const [current, setCurrent] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false);
  const changePassword = async () => { if (password.length < 8) return Alert.alert('Use at least 8 characters'); if (password !== confirm) return Alert.alert('Passwords do not match'); setBusy(true); try { if (!app.admin?.email) throw new Error('Admin email is unavailable.'); const { error: verifyError } = await supabase.auth.signInWithPassword({ email: app.admin.email, password: current }); if (verifyError) throw new Error('Current password is incorrect.'); const { error } = await supabase.auth.updateUser({ password }); if (error) throw error; setCurrent(''); setPassword(''); setConfirm(''); Alert.alert('Password updated'); } catch (e) { Alert.alert('Could not change password', message(e)); } finally { setBusy(false); } };
  return <Screen><Heading title="Profile" subtitle="Your signed-in administrator account." /><Card><View style={styles.avatar}><Text style={styles.avatarText}>{(app.admin?.name || 'A').charAt(0).toUpperCase()}</Text></View><Text style={styles.name}>{app.admin?.name}</Text><Text style={styles.email}>{app.admin?.email}</Text><View style={styles.role}><Text style={styles.roleText}>{app.admin?.role || 'Admin'}</Text></View></Card><Card title="Change password"><Field label="Current password" value={current} onChangeText={setCurrent} secureTextEntry /><Field label="New password" value={password} onChangeText={setPassword} secureTextEntry /><Field label="Confirm password" value={confirm} onChangeText={setConfirm} secureTextEntry /><Button label="Update password" onPress={changePassword} loading={busy} /></Card><Button label="Sign out" tone="danger" icon="log-out-outline" onPress={() => supabase.auth.signOut()} /></Screen>;
}
const styles = StyleSheet.create({ toggle: { minHeight: 58, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, toggleLabel: { color: colors.ink, fontWeight: '600', flex: 1 }, exportCopy: { color: colors.muted, lineHeight: 20, marginBottom: spacing.sm }, avatar: { width: 76, height: 76, borderRadius: 24, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center', alignSelf: 'center' }, avatarText: { color: colors.white, fontWeight: '900', fontSize: 28 }, name: { color: colors.ink, fontWeight: '800', fontSize: 22, textAlign: 'center', marginTop: spacing.md }, email: { color: colors.muted, textAlign: 'center', marginTop: 4 }, role: { alignSelf: 'center', backgroundColor: '#EAF3FF', borderRadius: radius.pill, paddingHorizontal: 14, paddingVertical: 6, marginTop: 12 }, roleText: { color: colors.primary, fontWeight: '800' } });
