import React, { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { Ionicons } from '@expo/vector-icons';
import { Badge, Button, Card, Empty, Field, Heading, Row, Screen } from '../components/ui';
import { useApp } from '../context/AppContext';
import type { AdminProfile } from '../types';
import { message } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';

const blank = { name: '', email: '', password: '', role: 'Admin' };
export function UsersScreen({ navigation }: any) {
  const app = useApp(); const [form, setForm] = useState(blank); const [showCreate, setShowCreate] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [deleteTarget, setDeleteTarget] = useState<AdminProfile | null>(null); const [ownerPassword, setOwnerPassword] = useState('');
  const create = async () => { if (!form.name.trim() || !form.email.trim() || form.password.length < 6) return setError('Name, email, and a password of at least 6 characters are required.'); setBusy('create'); try { await app.createAdmin(form); setForm(blank); setShowCreate(false); } catch (e) { setError(message(e)); } finally { setBusy(''); } };
  const remove = async () => { if (!deleteTarget || !ownerPassword) return; setBusy('delete'); try { await app.deleteAdmin(deleteTarget, ownerPassword); setDeleteTarget(null); setOwnerPassword(''); } catch (e) { Alert.alert('Could not delete admin', message(e)); } finally { setBusy(''); } };
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><View style={styles.heading}><Heading title="All users" subtitle="Administrator access and customer app accounts." /><Pressable accessibilityLabel="Create admin" style={styles.add} onPress={() => { setError(''); setShowCreate(true); }}><Ionicons name="person-add" size={21} color={colors.white} /></Pressable></View>
    <Card title={`Administrators (${app.admins.length})`}>{app.admins.map(admin => <Row key={admin.id} title={admin.name} subtitle={`${admin.email} · ${admin.role}`} right={<View style={styles.rowActions}><Badge label={admin.active ? 'Allowed' : 'Disabled'} tone={admin.active ? 'success' : 'danger'} />{admin.id !== app.admin?.id ? <Pressable accessibilityLabel={`Delete ${admin.name}`} hitSlop={12} onPress={() => setDeleteTarget(admin)}><Ionicons name="trash-outline" size={19} color={colors.danger} /></Pressable> : null}</View>} />)}</Card>
    <Card title={`Customer users (${app.customers.length})`}>{app.customers.map(customer => <Row key={customer.id} title={customer.name} subtitle={`${customer.email || 'No email'} · ${customer.phone} · ${customer.auth_user_id ? 'App signup' : 'Admin record'}`} onPress={() => navigation.getParent()?.navigate('UserProfile', { customerId: customer.id })} right={<Ionicons name="chevron-forward" size={20} color={colors.muted} />} />)}{!app.customers.length ? <Empty icon="person-outline" title="No customer users" detail="Customer profiles will appear here." /> : null}</Card>
    <Modal visible={showCreate} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setShowCreate(false)}><Screen><View style={styles.heading}><Heading title="New administrator" subtitle="Create dashboard access for a team member." /><Pressable onPress={() => setShowCreate(false)}><Ionicons name="close" size={28} color={colors.ink} /></Pressable></View><Card>{error ? <Text style={styles.error}>{error}</Text> : null}<Field label="Full name" value={form.name} onChangeText={name => setForm({ ...form, name })} /><Field label="Email" value={form.email} onChangeText={email => setForm({ ...form, email })} autoCapitalize="none" keyboardType="email-address" /><Field label="Temporary password" value={form.password} onChangeText={password => setForm({ ...form, password })} secureTextEntry /><Text style={styles.label}>Role</Text><View style={styles.picker}><Picker selectedValue={form.role} onValueChange={role => setForm({ ...form, role })}><Picker.Item label="Admin" value="Admin" /><Picker.Item label="Manager" value="Manager" /><Picker.Item label="Owner" value="Owner" /></Picker></View><Button label="Create administrator" icon="shield-checkmark" onPress={create} loading={busy === 'create'} /></Card></Screen></Modal>
    <Modal visible={Boolean(deleteTarget)} transparent animationType="fade" onRequestClose={() => setDeleteTarget(null)}><View style={styles.scrim}><View style={styles.dialog}><Ionicons name="lock-closed" size={28} color={colors.danger} /><Text style={styles.dialogTitle}>Delete {deleteTarget?.name}?</Text><Text style={styles.dialogCopy}>Enter the owner password to confirm removal. At least one owner must remain.</Text><Field label="Owner password" value={ownerPassword} onChangeText={setOwnerPassword} secureTextEntry /><Button label="Delete administrator" tone="danger" onPress={remove} loading={busy === 'delete'} /><Button label="Cancel" tone="secondary" onPress={() => setDeleteTarget(null)} /></View></View></Modal>
  </Screen>;
}
const styles = StyleSheet.create({ heading: { flexDirection: 'row', justifyContent: 'space-between' }, add: { width: 50, height: 50, borderRadius: 16, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, rowActions: { alignItems: 'flex-end', gap: 10 }, error: { color: colors.danger, backgroundColor: '#FFF0F0', borderRadius: 10, padding: 12, marginBottom: spacing.md }, label: { color: colors.ink, fontWeight: '700', marginBottom: 7 }, picker: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, overflow: 'hidden', marginBottom: spacing.md }, scrim: { flex: 1, backgroundColor: colors.scrim, justifyContent: 'center', padding: spacing.lg }, dialog: { backgroundColor: colors.surface, padding: spacing.lg, borderRadius: radius.lg }, dialogTitle: { color: colors.ink, fontWeight: '900', fontSize: 21, marginTop: 12 }, dialogCopy: { color: colors.muted, lineHeight: 21, marginVertical: 12 } });
