import React, { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Badge, Button, Card, Empty, Field, Heading, Row, Screen, Stat } from '../components/ui';
import { useApp } from '../context/AppContext';
import { message } from '../lib/supabase';
import { colors, spacing } from '../theme';

const money = (v: number) => `PKR ${Number(v || 0).toLocaleString()}`;
export function UserProfileScreen({ route, navigation }: any) {
  const app = useApp(); const user = app.customers.find(x => x.id === route.params.customerId); const [temp, setTemp] = useState(''); const [ownerPassword, setOwnerPassword] = useState(''); const [busy, setBusy] = useState(false);
  const sales = useMemo(() => app.sales.filter(x => x.customer_id === user?.id), [app.sales, user?.id]); const orders = app.orders.filter(x => x.customer_id === user?.id); const invoices = app.invoices.filter(x => x.customer_id === user?.id);
  if (!user) return <Screen><Empty title="User not found" detail="The profile may have been removed." /></Screen>;
  const generate = () => { const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$'; setTemp(Array.from({ length: 12 }, () => alphabet[Math.floor(Math.random() * alphabet.length)]).join('')); };
  const reset = async () => { if (temp.length < 8 || !ownerPassword) return Alert.alert('Enter an 8+ character password and owner password.'); setBusy(true); try { await app.resetCustomerPassword(user.id, temp, ownerPassword); Alert.alert('Password updated', `A temporary password was set for ${user.name}. Share it securely.`); setTemp(''); setOwnerPassword(''); } catch (e) { Alert.alert('Could not reset password', message(e)); } finally { setBusy(false); } };
  const remove = () => Alert.alert('Remove customer profile?', 'This removes the customer and linked operational records. Type-level server protection still applies.', [{ text: 'Cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { try { await app.deleteCustomerProfile(user.id); navigation.goBack(); } catch (e) { Alert.alert('Could not remove profile', message(e)); } } }]);
  return <Screen refreshing={app.refreshing} onRefresh={app.refresh}><View style={styles.header}><Pressable style={styles.back} onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><View style={{ flex: 1 }}><Heading title={user.name} subtitle="Customer user profile" /></View></View><Card><View style={styles.identity}><View style={styles.avatar}><Text style={styles.initial}>{user.name.charAt(0)}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{user.name}</Text><Text style={styles.meta}>{user.email || 'No email'}</Text><Badge label={user.auth_user_id ? 'Customer app account' : 'Admin-created record'} tone={user.auth_user_id ? 'success' : 'default'} /></View></View><View style={styles.details}><Text style={styles.detail}><Ionicons name="call-outline" /> {user.phone}</Text><Text style={styles.detail}><Ionicons name="location-outline" /> {user.address}</Text><Text style={styles.detail}><Ionicons name="calendar-outline" /> Joined {new Date(user.created_at).toLocaleDateString()}</Text></View></Card><View style={styles.stats}><Stat icon="cart-outline" label="Orders" value={orders.length} /><Stat icon="water-outline" label="Purchases" value={sales.length} tone={colors.cyan} /><Stat icon="cash-outline" label="Lifetime value" value={money(sales.reduce((a, x) => a + Number(x.total_amount), 0))} tone={colors.success} /><Stat icon="document-text-outline" label="Invoices" value={invoices.length} tone="#8B5CF6" /></View><Card title="Recent activity">{orders.slice(0, 3).map(x => <Row key={x.id} title={`${x.bottle_type} × ${x.quantity}`} subtitle={`Order · ${x.status}`} />)}{sales.slice(0, 3).map(x => <Row key={x.id} title={`${x.bottle_type} × ${x.quantity}`} subtitle={`Sale · ${new Date(x.created_at).toLocaleDateString()}`} right={<Text style={styles.amount}>{money(x.total_amount)}</Text>} />)}</Card>{user.auth_user_id && app.admin?.role === 'Owner' ? <Card title="Account recovery"><View style={styles.passwordRow}><View style={{ flex: 1 }}><Field label="Temporary password" value={temp} onChangeText={setTemp} /></View><Button compact label="Generate" tone="secondary" onPress={generate} /></View><Field label="Owner password" value={ownerPassword} onChangeText={setOwnerPassword} secureTextEntry /><Button label="Set temporary password" onPress={reset} loading={busy} /></Card> : null}<Button label="Open customer ledger" icon="book-outline" onPress={() => navigation.replace('CustomerDetail', { customerId: user.id })} /><Button label="Remove profile" tone="danger" onPress={remove} /></Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', gap: 10 }, back: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border }, identity: { flexDirection: 'row', alignItems: 'center', gap: 14 }, avatar: { width: 70, height: 70, borderRadius: 23, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, initial: { color: colors.white, fontWeight: '900', fontSize: 26 }, name: { color: colors.ink, fontSize: 21, fontWeight: '900' }, meta: { color: colors.muted, marginVertical: 5 }, details: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.md, paddingTop: spacing.md, gap: 8 }, detail: { color: colors.muted, lineHeight: 20 }, stats: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, amount: { color: colors.ink, fontWeight: '900', fontSize: 12 }, passwordRow: { flexDirection: 'row', alignItems: 'center', gap: 8 } });
